accounts/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', views.LoginView.as_view(), name='login'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('users/', include([

        path('my-courses', views.EnrolledCoursesListView.as_view(),
             name='enrolled-courses'),
        path('my-courses/<slug:slug>/view',
             views.StartLessonView.as_view(), name='course-lessons'),
        path('my-courses/<slug:slug>/lessons/<int:id>',
             views.LessonView.as_view(), name='course-lessons-single'),
        path('profile', views.ProfileUpdateView.as_view(), name='my-profile'),

    ]) 
    ),
] 

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<slug:slug>/', views.cart_add, name='cart_add'),
    path('remove/<slug:slug>', views.cart_remove, name='cart_remove'),
    path('checkout', views.cart_checkout, name='cart_checkout'),
]

courses/urls.py
from django.urls import path
from .views import *

app_name = 'courses'

urlpatterns = [
    path('courses/<slug:slug>', CourseDetailView.as_view(), name='course-details'),
    path('courses/<slug:slug>/category', CoursesByCategoryListView.as_view(), name='course-by-category'),
]

udemy/urls.py
from django.urls import path
from .views import *

app_name = 'udemy'

urlpatterns = [
    path('', HomeListView.as_view(), name='home'),
    path('search', SearchView.as_view(), name='search'),
]

udemyclone/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from udemyclone import settings

admin.site.site_header = "EduFlix Admin"
admin.site.site_title = "EduFlix Admin Portal"
admin.site.index_title = "Welcome to EduFlix Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('accounts.urls')),
    path('', include('udemy.urls')),
    path('', include('courses.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddCourseForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST

from courses.models import Course
from udemy.models import Enroll
from .cart import Cart


@require_POST
def cart_add(request, slug):
    cart = Cart(request)  # create a new cart object passing it the request object
    course = get_object_or_404(Course, slug=slug)
    cart.add(course=course, quantity=1, update_quantity=False)
    return redirect('cart:cart_detail')


def cart_remove(request, slug):
    cart = Cart(request)
    course = get_object_or_404(Course, slug=slug)
    cart.remove(course)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})


@login_required(login_url='/login')
def cart_checkout(request):
    carts = Cart(request)
    for cart in carts:
        course = cart['course']
        # course = get_object_or_404(Course, slug=course.slug)
        Enroll.objects.create(course=course, user_id=request.user.id)
    messages.success(request, 'Successfully checked out!')
    carts.clear()
    return redirect(reverse_lazy('cart:cart_detail'))

templates/partials/cart.html
{% load static %}

<div class="icon">
    <a href=""><i class="fas fa-shopping-cart"></i></a>
    {% with total_items=cart|length %}
        {% if cart|length > 0 %}
            <span class="number">{{ cart|length }}</span>
        {% else %}
            <span class="number">0</span>
        {% endif %}
    {% endwith %}
</div>
<div class="dropdown course-list-dropdown corner-triangle top-right">
    <div class="list-wrapper">
        <div class="item-list">
            <ul>
                {% with total_items=cart|length %}
                    {% if cart|length > 0 %}
                        {% for item in cart %}
                            {% with course=item.course %}
                                <li>
                                    <div class="item clearfix">
                                        <div class="item-image">
                                            <a href="">
                                                <img src="{% static 'images/learning.jpg' %}" alt="" class="img-fluid">
                                            </a>
                                        </div>
                                        <div class="item-details">

                                            {#                                    <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">#}
                                            {#                                        {{ total_items }} item {{ total_items|pluralize }},#}
                                            {#                                        Kshs. {{ cart.get_total_price }}#}
                                            {#                                    </a>#}
                                            <a href="#">
                                                <div class="course-name">{{ course.title }}</div>
                                                {#                                                <div class="instructor-name">first_name last_name</div>#}
                                                <div class="item-price">
                                                    <span class="current-price">₹{{ course.price }}</span>
                                                    {#                                    {{ --<span class="original-price">$300</span>--}}#}
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                </li>
                            {% endwith %}
                        {% endfor %}
                    {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </ul>
        </div>
        <div class="dropdown-footer">
            <div class="cart-total-price clearfix">
                <span>Total:</span>
                <div class="float-right">
                    <span class="current-price">₹{{ cart.get_total_price }}</span>
                </div>
            </div>
            <a href="{% url 'cart:cart_detail' %}">Go to cart</a>
        </div>
    </div>
    <div class="empty-box text-center d-none">
        <p>Your cart is empty.</p>
        <a href="">Keep Shopping</a>
    </div>
</div>

templates/partials/header.html
{% load static %}

<link rel="favicon" href="{% static 'frontend/img/icons/favicon.ico' %}">
<link rel="apple-touch-icon" href="{% static 'frontend/img/icons/icon.png' %}">
<link rel="stylesheet" href="{% static 'frontend/css/jquery.webui-popover.min.css' %}">
<link rel="stylesheet" href="{% static 'frontend/css/select2.min.css' %}">
<link rel="stylesheet" href="{% static 'frontend/css/slick.css' %}">
<link rel="stylesheet" href="{% static 'frontend/css/slick-theme.css' %}">
<link rel="stylesheet" href="{% static 'frontend/css/fontawesome-all.min.css' %}">
<link rel="stylesheet" href="{% static 'frontend/css/bootstrap.min.css' %}">
{% comment %} <link rel="stylesheet" href="{% static 'frontend/css/bootstrap5.min.css' %}"> {% endcomment %}
<link rel="stylesheet" href="{% static 'frontend/css/main.css' ?{% now "U" %}">
<link rel="stylesheet" href="{% static 'frontend/css/responsive.css' %}">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700" rel="stylesheet">
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css"> 

templates/partials/menu.html
<div class="main-nav-wrap">
    <div class="mobile-overlay"></div>

    <ul class="mobile-main-nav">
        <div class="mobile-menu-helper-top"></div>

        <li class="has-children"">
            <a href="">
                <i class="fas fa-th icon-bold d-inline" ></i>
                <span  style="font-size:15px; font-weight: bold; color:"#0464fc";>Categories</span>
                <span class="has-sub-category"><i class="fas fa-angle-right"></i></span>
            </a>

            <ul class="category corner-triangle top-left is-hidden">
                <li class="go-back">
                    <a href=""><i class="fas fa-angle-left"></i>Menu</a>
                </li>

                {% for category in categories %}
                    <li>
                        <a href="{% url 'courses:course-by-category' category.slug %}">
                            <span class="icon"><i class="fa fa-caret-right"></i></span>
                            <span>{{ category.title }}</span>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </li>

        <div class="mobile-menu-helper-bottom"></div>
    </ul>
</div>

templates/partials/navbar.html
{% load static %}

<section class="menu-area">
    <div class="container-xl">
        <div class="row">
            <div class="col">
                <nav class=" navbar navbar-expand-lg navbar-white bg-white">

                    <ul class="mobile-header-buttons">
                        <li><a class="mobile-nav-trigger" href="#mobile-primary-nav">Menu<span></span></a></li>
                        <li><a class="mobile-search-trigger" href="#mobile-search">Search<span></span></a></li>
                    </ul>

                    <a class="navbar-brand" style="color:#0464fc" href="/">
                        {#                        {{ --<img src="" alt="" height="30">--}}#}
                        EduFlix
                    </a>

                    {% include 'partials/menu.html' %}

                    <form class="inline-form mr-auto" action="{% url 'udemy:search' %}" method="get" style="width: 50%;">
                        <div class="input-group search-box mobile-search">
                            <input type="text" name='q' class="form-control"
                                   placeholder="Search for courses">
                            <div class="input-group-append">
                                <button class="btn" type="submit"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                    </form>

                    <div class="wishlist-box menu-icon-box" id="wishlist_items">
                        {#                        Wishlist will be here#}
                    </div>

                                       
                    {% if request.user.is_authenticated %}
                        <span class="signin-box-move-desktop-helper"></span>
                        
                        <div class="sign-in-box btn-group">
                            <a href="{% url 'accounts:enrolled-courses' %}" class=" btn btn-sign-in">My Learnings</a>
                        </div>
                        
                        <div class="cart-box menu-icon-box" id="cart_items"> 
                             {% include 'partials/cart.html' %}
                        </div>

                        <div class="user-box menu-icon-box">
                            <div class="icon">
                                <a href="">
                                    <img src="{% static 'images/avatar.png' %}" alt="" class="img-fluid">
                                </a>
                            </div>
                            <div class="dropdown user-dropdown corner-triangle top-right">
                                <ul class="user-dropdown-menu">

                                    <li class="dropdown-user-info">
                                        <a href="">
                                            <div class="clearfix">
                                                <div class="user-image float-left">
                                                    <img src="{% static 'images/avatar.png' %}" alt=""
                                                         class="img-fluid">
                                                </div>
                                                <div class="user-details">
                                                    <div class="user-name">
                                                        <span class="hi">hi,</span> {{ request.user.email }}
                                                    </div>
                                                    <div class="user-email">
                                                        <span class="email">{{ request.user.name }}</span>
                                                        <span class="welcome">Welcome back</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </a>
                                    </li>

                                    <li class="user-dropdown-menu-item">
                                        <a href="{% url 'accounts:enrolled-courses' %}">
                                            <i class="far fa-gem"></i>Enrolled Courses
                                        </a>
                                    </li>
                                    {% comment %} <li class="user-dropdown-menu-item">
                                        <a href="">
                                            <i class="far fa-heart"></i>My Wishlist
                                        </a>
                                    </li> {% endcomment %}
                                    <li class="user-dropdown-menu-item">
                                        <a href="{% url 'accounts:my-profile' %}">
                                            <i class="fas fa-user"></i>Profile Edit
                                        </a>
                                    </li>
                                    <li class="dropdown-user-logout user-dropdown-menu-item">
                                        <a href="{% url 'accounts:logout' %}">Logout</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    {% else %}
                        <span class="signin-box-move-desktop-helper"></span>
                        <div class="sign-in-box btn-group">

                            <a href="{% url 'accounts:register' %}" class="btn btn-sign-in">Teach on Eduflix</a>

                            <a href="{% url 'accounts:login' %}" class="btn btn-sign-in">Login</a>

                            <a href="{% url 'accounts:register' %}" class="btn btn-sign-up">Sign up</a>

                        </div>
                    {% endif %}
                </nav>
            </div>
        </div>
    </div>
</section>

templates/partials/scripts.html
{% load static %}

<script src="{% static 'frontend/js/vendor/modernizr-3.5.0.min.js'  %}"></script>
<script src="{% static 'frontend/js/vendor/jquery-3.2.1.min.js'  %}"></script>
<script src="{% static 'frontend/js/popper.min.js'  %}"></script>
<script src="{% static 'frontend/js/bootstrap.min.js'  %}"></script>
{% comment %} <script src="{% static 'frontend/js/bootstrap5.bundle.min.js'  %}"></script> {% endcomment %}
<script src="{% static 'frontend/js/slick.min.js'  %}"></script>
<script src="{% static 'frontend/js/select2.min.js'  %}"></script>
<script src="{% static 'frontend/js/tinymce.min.js'  %}"></script>
<script src="{% static 'frontend/js/multi-step-modal.js'  %}"></script>
<script src="{% static 'frontend/js/jquery.webui-popover.min.js'  %}"></script>
<script src="{% static 'frontend/js/main.js'  %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
{% block scripts %}{% endblock %}